platform: linux

inputs:
  - name: app-resource
  - name: build-triggers-resource
  - name: ci-resource

outputs:
  - name: updated-build-triggers

run:
  path: ./ci-resource/tasks/update-build-triggers.sh

image_resource:
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: git